// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewProvider struct {
	UserID string `json:"userId"`
}

type Provider struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
}

type Query struct {
}
