FROM ghcr.io/linuxserver/baseimage-selkies:ubuntunoble

# title
ENV TITLE=Discord \
    NO_GAMEPAD=true

RUN \
  echo "**** add icon ****" && \
  curl -o \
    /usr/share/selkies/www/icon.png \
    https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/webcord-icon.png && \
  echo "**** install packages ****" && \
  apt-key adv \
    --keyserver hkp://keyserver.ubuntu.com:80 \
    --recv-keys 5301FA4FD93244FBC6F6149982BB6851C64F6880 && \
  echo \
    "deb https://ppa.launchpadcontent.net/xtradeb/apps/ubuntu noble main" > \
    /etc/apt/sources.list.d/xtradeb.list && \
  apt-get update && \
  curl -L -o discord.deb "https://discord.com/api/download?platform=linux&format=deb" && \
  apt-get install -y libatk1.0-0t64 libatk-bridge2.0-0t64 libgtk-3-0t64 && \
  apt-get install -y ./discord.deb && \
  rm ./discord.deb && \
  mkdir -p $HOME/.config/discord/ && \
  echo '{"SKIP_HOST_UPDATE": true}' > $HOME/.config/discord/settings.json &&\
  rm -rf \
    /var/lib/apt/lists/* \
    /var/tmp/* \
    /tmp/*

# add local files
COPY /root /

# ports and volumes
EXPOSE 3000

VOLUME /config
