env_files = [
    { path = "./.env", profile = "development" },
    { path = "./.env.staging", profile = "staging" },
    { path = "./.env.production", profile = "production" },
]

[tasks.install-target-wasm]
command = "rustup"
args = ["target", "add", "wasm32-unknown-unknown"]

[tasks.install-trunk]
install_crate = "trunk"

[tasks.install-wasm-bindgen-cli]
install_crate = "wasm-bindgen-cli"

[tasks.serve]
command = "trunk"
args = ["serve"]
dependencies = [
    "install-target-wasm",
    "install-trunk",
    "install-wasm-bindgen-cli",
]

[tasks.s]
alias="serve"

[tasks.create-package]
script = '''
trunk build --release
(cd dist && zip -r - .)>dist.zip
'''
