// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CityMunicipality struct {
	ID                   int    `json:"id"`
	PsgcCode             string `json:"psgcCode"`
	Name                 string `json:"name"`
	RegionCode           string `json:"regionCode"`
	ProvinceCode         string `json:"provinceCode"`
	CityMunicipalityCode string `json:"cityMunicipalityCode"`
}

type Country struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	Alpha2       string `json:"alpha2"`
	Alpha3       string `json:"alpha3"`
	PhoneCode    string `json:"phoneCode"`
	CurrencyCode string `json:"currencyCode"`
}

type GlobalRole struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Province struct {
	ID           int    `json:"id"`
	PsgcCode     string `json:"psgcCode"`
	Name         string `json:"name"`
	RegionCode   string `json:"regionCode"`
	ProvinceCode string `json:"provinceCode"`
}

type Query struct {
}

type Region struct {
	ID         int    `json:"id"`
	PsgcCode   string `json:"psgcCode"`
	Name       string `json:"name"`
	RegionCode string `json:"regionCode"`
}
