// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Address struct {
	ID            int    `json:"id"`
	UserID        int    `json:"userId"`
	StreetAddress string `json:"streetAddress"`
	Locality      string `json:"locality"`
	Region        string `json:"region"`
	PostalCode    string `json:"postalCode"`
	Country       string `json:"country"`
	Primary       bool   `json:"primary"`
}

type ChangeUserInfo struct {
	UserID      int         `json:"userId"`
	BirthDate   time.Time   `json:"birthDate"`
	BirthGender BirthGender `json:"birthGender"`
}

type ChangeUserKyc struct {
	UserID     int    `json:"userId"`
	FirstName  string `json:"firstName"`
	LastName   string `json:"lastName"`
	MiddleName string `json:"middleName"`
}

type LinkAddress struct {
	UserID    int `json:"userId"`
	AddressID int `json:"addressId"`
}

type LinkEmailAddress struct {
	UserID         int `json:"userId"`
	EmailAddressID int `json:"emailAddressId"`
}

type LinkPhoneNumber struct {
	UserID        int `json:"userId"`
	PhoneNumberID int `json:"phoneNumberId"`
}

type Mutation struct {
}

type NewAddress struct {
	UserID        int    `json:"userId"`
	StreetAddress string `json:"streetAddress"`
	Locality      string `json:"locality"`
	Region        string `json:"region"`
	PostalCode    string `json:"postalCode"`
	Country       string `json:"country"`
}

type NewEmailAddress struct {
	UserID       int    `json:"userId"`
	EmailAddress string `json:"emailAddress"`
}

type NewPhoneNumber struct {
	UserID      int    `json:"userId"`
	PhoneNumber string `json:"phoneNumber"`
}

type NewUploadAvatar struct {
	UserID    int            `json:"userId"`
	ImageFile graphql.Upload `json:"imageFile"`
}

type NewUser struct {
	ZitadelID    string `json:"zitadelId"`
	Username     string `json:"username"`
	PrimaryEmail string `json:"primaryEmail"`
	DisplayName  string `json:"displayName"`
}

type NewUserFull struct {
	ZitadelID    string      `json:"zitadelId"`
	Username     string      `json:"username"`
	PrimaryEmail string      `json:"primaryEmail"`
	DisplayName  string      `json:"displayName"`
	BirthDate    time.Time   `json:"birthDate"`
	BirthGender  BirthGender `json:"birthGender"`
	FirstName    string      `json:"firstName"`
	LastName     string      `json:"lastName"`
	MiddleName   string      `json:"middleName"`
}

type NewUserInfo struct {
	UserID      int         `json:"userId"`
	BirthDate   time.Time   `json:"birthDate"`
	BirthGender BirthGender `json:"birthGender"`
}

type NewUserProfile struct {
	UserID      int         `json:"userId"`
	DisplayName string      `json:"displayName"`
	FirstName   string      `json:"firstName"`
	LastName    string      `json:"lastName"`
	MiddleName  string      `json:"middleName"`
	BirthDate   time.Time   `json:"birthDate"`
	BirthGender BirthGender `json:"birthGender"`
}

type PhoneNumber struct {
	ID          int        `json:"id"`
	UserID      int        `json:"userId"`
	PhoneNumber string     `json:"phoneNumber"`
	Primary     bool       `json:"primary"`
	VerifiedAt  *time.Time `json:"verifiedAt,omitempty"`
}

type Query struct {
}

type UserKyc struct {
	ID         int        `json:"id"`
	UserID     int        `json:"userId"`
	FirstName  string     `json:"firstName"`
	LastName   string     `json:"lastName"`
	MiddleName string     `json:"middleName"`
	VerifiedAt *time.Time `json:"verifiedAt,omitempty"`
}
